// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqww8ABDjLfhxaiefSwwkMQDNSqQ1pObo',
    appId: '1:135142478964:web:47f0682674cfd24d64ad21',
    messagingSenderId: '135142478964',
    projectId: 'fir-d-demo-7b682',
    authDomain: 'fir-d-demo-7b682.firebaseapp.com',
    storageBucket: 'fir-d-demo-7b682.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUeD0RUy7wk5_uofjdho5xfERikvJIRNs',
    appId: '1:135142478964:android:0f47a250c1a3309564ad21',
    messagingSenderId: '135142478964',
    projectId: 'fir-d-demo-7b682',
    storageBucket: 'fir-d-demo-7b682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWkAJloG7dblF6af49luumzi6lMd-Ycw',
    appId: '1:135142478964:ios:3b9e24579b45beb764ad21',
    messagingSenderId: '135142478964',
    projectId: 'fir-d-demo-7b682',
    storageBucket: 'fir-d-demo-7b682.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqww8ABDjLfhxaiefSwwkMQDNSqQ1pObo',
    appId: '1:135142478964:web:cdab59b7b0002c3b64ad21',
    messagingSenderId: '135142478964',
    projectId: 'fir-d-demo-7b682',
    authDomain: 'fir-d-demo-7b682.firebaseapp.com',
    storageBucket: 'fir-d-demo-7b682.firebasestorage.app',
  );
}
